name: Clone Doku Repository

on:
  schedule:
    - cron: '0 17 * * *'  # Daily sync at 5pm
  workflow_dispatch:  

jobs:
  mirror:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: 
          - { name: 'pcg-gcp/gcp-mco-repo-test-mirror', token: 'GCP_MCO_SOURCE_MIRROR_TOKEN', path: 'source_repo' }
          - { name: 'pcg-gcp/gcp-mco-additional-source-mirror-repo', token: 'GCP_MCO_ADDITIONAL_SOURCE_MIRROR_TOKEN', path: 'source_repo2' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo.name }}
          token: ${{ secrets[matrix.repo.token] }}
          path: ${{ matrix.repo.path }}
          fetch-depth: 0    # avoid shallow clone

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: cw-jimmy-cu/gcp-mco-target-repo-mirror
          token: ${{ secrets.TEST_MCO_TARGET_MIRROR_TOKEN }}
          path: target_repo
          fetch-depth: 0   # avoid shallow clone

      - name: Set up SSH for target repository
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_TARGET }}

      - name: Sync source with target
        run: |
          git config --global user.email "jimmy.cu@pcg.io"
          git config --global user.name "Jimmy Cu"

          # Ensure we are in the right directory
          cd target_repo
          
          # Check if the source_content directory exists
          if [ ! -d "source_content" ]; then
            echo "source_content directory does not exist. Using cp to initialize."
            mkdir -p source_content
            cp -r ../${{ matrix.repo.path }}/* source_content/
          else
            echo "source_content directory exists. Using rsync to sync."
            rsync -av --delete ../${{ matrix.repo.path }}/ source_content/
          fi
          
          # Add changes to git
          git add .
          
          # Commit changes
          git commit -m "Sync with source repository"
          
          # Push changes
          git push origin main