name: Clone Doku Repository

on:
  schedule:
    - cron: '0 17 * * *'  # Diese Zeile gibt an, dass die Aktion täglich um 17:00 Uhr UTC ausgeführt wird
  workflow_dispatch:  # Ermöglicht das manuelle Auslösen der Aktion

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: pcg-gcp/gcp-mco-repo-test-mirror
          token: ${{ secrets.GCP_MCO_SOURCE_MIRROR_TOKEN }}
          path: source_repo
          fetch-depth: 0

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: cw-jimmy-cu/gcp-mco-target-repo-mirror
          token: ${{ secrets.TEST_MCO_TARGET_MIRROR_TOKEN }}
          path: target_repo
          fetch-depth: 0

      - name: Set up SSH for target repository
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_TARGET }}

      - name: Sync source with target
        run: |
          cd target_repo
          git remote add source ../source_repo
          git fetch source
          git merge source/main --allow-unrelated-histories -m "Sync with source repository"
          git push origin main
