name: Mirror Repository

on:
  schedule:
    - cron: '0 17 * * *'  # Diese Zeile gibt an, dass die Aktion täglich um 17:00 Uhr UTC ausgeführt wird
  workflow_dispatch:  # Ermöglicht das manuelle Auslösen der Aktion

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: cw-jimmy-cu/gcp-mco-target-repo-mirror
          token: ${{ secrets.TEST_MCO_TARGET_MIRROR_TOKEN }}
          fetch-depth: 0

      - name: Fetch source repository
        run: |
          git remote add source https://$GCP_MCO_SOURCE_MIRROR_TOKEN@github.com/pcg-gcp/gcp-mco-repo-test-mirror.git
          git fetch source
        env:
          GCP_MCO_SOURCE_MIRROR_TOKEN: ${{ secrets.GCP_MCO_SOURCE_MIRROR_TOKEN }}

      - name: Sync source with target
        run: |
          git checkout main
          git merge source/main --allow-unrelated-histories -m "Sync with source repository"
          git push origin main
