name: Clone Doku Repository

on:
  schedule:
    - cron: '0 17 * * *'  # Tägliche Ausführung um 17 Uhr UTC
  workflow_dispatch:  # Manuelle Auslösung

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: pcg-gcp/gcp-mco-repo-test-mirror
          token: ${{ secrets.GCP_MCO_SOURCE_MIRROR_TOKEN }}
          path: source_repo
          fetch-depth: 0

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: cw-jimmy-cu/gcp-mco-target-repo-mirror
          token: ${{ secrets.TEST_MCO_TARGET_MIRROR_TOKEN }}
          path: target_repo
          fetch-depth: 0

      - name: Set up SSH for target repository
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_TARGET }}

      - name: Sync source with target
        run: |

          # Ensure we are in the right directory
          cd target_repo
          
          # Clean the target repository except for .git directory
          find . -mindepth 1 -not -name '.git' -exec rm -rf {} +

          # Create new folder
          mkdir -p target_repo/source_content

          # Copy content from source repo to the target repo
          cp -r ../source_repo/* target_repo/source_content

          cd ..

          git add .
          
