name: Mirror Repository

on:
  schedule:
    - cron: '0 17 * * *'  
  workflow_dispatch:  

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: pcg-gcp/gcp-mco-repo-test-mirror
          token: ${{ secrets.SOURCE_GITHUB_MIRROR_TOKEN }}

      - name: Push to target repository
        run: |
          git remote add target https://github.com/cw-jimmy-cu/gcp-mco-target-repo-mirror.git
          git push --mirror target
        env:
          TARGET_GITHUB_TOKEN: ${{ secrets.TARGET_GITHUB_MIRROR_TOKEN }}
